name: 'Verify Konveyor PRs'
description: 'Verify PRs for the KubeBuilder project repos & similar'
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v3
  - name: Run verify
    run: pwd && ls -lhat && go run ${GITHUB_ACTION_PATH}/verify.go
    shell: bash
