name: Handle Issue Comment

on:
  issue_comment:

jobs:
  reconcile-issue-comment:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/reconcile-issue-comment.yaml
